# -*- coding: utf-8 -*-
"""Copy of train_rq_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edoR97wHkjirzS6Gf9zGSFrBYK9oHXuH
"""

from google.colab import drive
drive.mount('/content/drive')

# Copy repo to local runtime (fast SSD)
#!cp -r /content/drive/MyDrive/Colab\ Notebooks/GLiNER_Modular_RAG /content/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/GLiNER_Modular_RAG
!pwd

!pip install -r requirements.txt
!pip install -e .

import json, random, torch
import time
from pathlib import Path
from src import RAGRetriever
from src import GLiNERRagCrossAttn

PATH_TRAIN_DATA = Path("data/combined_dataset/train.jsonl")
PATH_VAL_DATA = Path("data/combined_dataset/validation.jsonl")
PATH_TEST_DATA = Path("data/combined_dataset/test.jsonl")
PATH_TRAIN_DATA_RAG = Path('data/combined_dataset/train_w_rag.pkl')
PATH_VAL_DATA_RAG = Path('data/combined_dataset/VAL_w_rag.pkl')

BATCH_SIZE, EPOCHS, MAX_SAMPLES = 32, 50, 8
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Only pass tensors to device, keep other batch items (like id_to_classes dict) on CPU for collator decoding.
def to_dev(batch):
    return {k: (v.to(DEVICE) if torch.is_tensor(v) else v) for k, v in batch.items()}

def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

def align_for_bce(logits: torch.Tensor, target: torch.Tensor):
    # BCEWithLogitsLoss requires logits and target to have exactly the same shape.
    if logits.shape == target.shape:
        return logits, target

    # Common GLiNER case: labels are [B, L*K, C] while logits are [B, L, K, C].
    if target.dim() == 3 and logits.dim() == 4:
        b, lk, c = target.shape
        _, l, k, c_logits = logits.shape
        if lk == l * k and c == c_logits:
            return logits, target.view(b, l, k, c)

    # Reverse case: logits flattened but labels are 4D.
    if target.dim() == 4 and logits.dim() == 3:
        b, l, k, c = target.shape
        b2, lk, c_logits = logits.shape
        if b == b2 and lk == l * k and c == c_logits:
            return logits.view(b, l, k, c), target

    raise RuntimeError(
        f"Label/logit shape mismatch for BCE: logits={tuple(logits.shape)}, target={tuple(target.shape)}"
    )

# Prepare data for training
# raw = [json.loads(x) for x in DATA_PATH.open(encoding="utf-8") if x.strip()][:MAX_SAMPLES]
# data = [to_sample(x) for x in raw]
# # Clean up data by checking if it has at least one entity annotation, else skip sample.
# data = [x for x in data if x["ner"]]
def load_dataset(filepath, max_samples=None):
    """Helper function to load and format JSONL data."""
    dataset = []
    if not filepath.exists():
        print(f"Warning: File not found -> {filepath}")
        return dataset

    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip(): continue
            sample = json.loads(line)
            if "ner" in sample:
                sample["tokenized_text"] = sample.pop("tokens")
                dataset.append(sample)
    if max_samples:
        dataset = dataset[:max_samples]
    return dataset


def fn_rag_context (data, retriever, num_print=5):
    contexts = []
    for i, sample in enumerate(data):
        query_text = " ".join(sample["tokenized_text"])
        retrieved_context = retriever.retrieve_context(query_text)
        contexts.append(retrieved_context)

        if i < num_print:
            print(f"{i}. {query_text}")
            print(f"{i}. {retrieved_context}")
            print("-" * 50)
    return contexts

def fn_aggre_labels (data):
  label_set = set()
  for sample in data:
    for span in sample["ner"]:
        label_set.add(span[2])
  labels = sorted(label_set)
  return labels

def binary_accuracy(preds, y):
  """
  Returns accuracy per batch, i.e. if you get 8/10 right, this returns 0.8, NOT 8
  """
  #round predictions to the closest integer
  rounded_preds = torch.round(torch.sigmoid(preds))
  correct = (rounded_preds == y).float() #convert into float for division
  acc = correct.sum() / len(correct)
  return acc

# --- 1. Data Loading ---
print("Loading datasets...")
# Should remove the MAX_SAMPLES for complete training
train_data = load_dataset(PATH_TRAIN_DATA)
val_data = load_dataset(PATH_VAL_DATA)
test_data = load_dataset(PATH_TEST_DATA)
print(f'Number of training examples: {len(train_data)}')
print(f'Number of validation examples: {len(val_data)}')
print(f'Number of testing examples: {len(test_data)}')

# To create a global label set for the taining run
labels = fn_aggre_labels(train_data)
print(f"Target labels: {labels}")

# Build RAG context once for every sample before training to eliminate bottleneck of retrieving context every training step.
retriever = RAGRetriever(k=3)
print("RAG retriever enabled.")

import pickle

train_data_rag = []
train_data_rag = fn_rag_context(train_data, retriever, num_print=5)

val_data_rag = []
val_data_rag = fn_rag_context(val_data, retriever, num_print=5)
print("RAG retriever done.")

with open(PATH_TRAIN_DATA_RAG, 'wb') as f:
    pickle.dump(train_data_rag, f)

with open(PATH_VAL_DATA_RAG, 'wb') as f:
    pickle.dump(val_data_rag, f)

import pickle
with open(PATH_TRAIN_DATA_RAG, 'rb') as f:
  train_contexts = pickle.load(f)

with open(PATH_VAL_DATA_RAG, 'rb') as f:
  val_contexts = pickle.load(f)

def fn_train_batch(model, collator, train_data, train_data_rag, BATCH_SIZE, optimizer, criterion):
    epoch_loss = 0
    epoch_acc = 0

    model.train()

    # Create a list of all indices and shuffle it once per epoch
    all_idxs = list(range(len(train_data)))
    random.shuffle(all_idxs)

    for i in range(0, len(all_idxs), BATCH_SIZE):

        # Prepare data
        idxs = all_idxs[i:i+BATCH_SIZE]
        train_data_b = [train_data[i] for i in idxs]
        train_data_rag_b = [train_data_rag[i] for i in idxs]
        batch_inputs, batch_ctx_ids, batch_ctx_mask = fn_prepare_batch(model, collator, train_data_b, train_data_rag_b)

        # Clear old gradients from previous step.
        optimizer.zero_grad()

        # Send to model for training
        prediction_logits = model(batch_ctx_ids, batch_ctx_mask,**batch_inputs)

        # Calculate accuracy & loss
        target = batch_inputs["labels"].float()
        prediction_logits, target = align_for_bce(prediction_logits, target)
        loss = criterion(prediction_logits, target)
        acc = binary_accuracy(prediction_logits, target)

        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
        epoch_acc += acc.item()

    return epoch_loss / len(iterator), epoch_acc / len(iterator)

def fn_eval_batch(model, collator, val_data, val_data_rag, BATCH_SIZE, optimizer, criterion):
    epoch_loss = 0
    epoch_acc = 0

    model.eval()

    # don't have to shuffle every epoch
    all_idx = list(range(len(val_data)))

    with torch.no_grad():
      for i in range(0, len(all_idxs), BATCH_SIZE):

          # Prepare data
          idxs = all_idxs[i:i+BATCH_SIZE]
          val_data_b = [val_data[i] for i in idxs]
          val_data_rag_b = [val_data_rag[i] for i in idxs]
          batch_inputs, batch_ctx_ids, batch_ctx_mask = fn_prepare_batch(model, collator, val_data_b, val_data_rag_b)

          # Send to model for training
          prediction_logits = model(batch_ctx_ids, batch_ctx_mask,**batch_inputs)

          # Calculate accuracy & loss
          target = batch_inputs["labels"].float()
          prediction_logits, target = align_for_bce(prediction_logits, target)
          loss = criterion(prediction_logits, target)
          acc = binary_accuracy(prediction_logits, target)

          epoch_loss += loss.item()
          epoch_acc += acc.item()

    return epoch_loss / len(iterator), epoch_acc / len(iterator)

def fn_prep_batch(model, collator, train_data_b, train_data_rag_b):
  label_b = [labels for _ in train_data_b]
  batch_inputs = to_dev(collator(train_data_b, label_b))

  # Use retrieved context for cross-attention.
  batch_ctx_text = [train_data_rag_b[i] for i in idxs]
  batch_ctx = model.tokenizer(
      batch_ctx_text, return_tensors="pt", padding=True, truncation=True, max_length=model.gliner.config.max_len
  )

  batch_ctx_ids = batch_ctx["input_ids"].to(DEVICE)
  batch_ctx_mask = batch_ctx["attention_mask"].to(DEVICE).long()

  if batch_ctx_ids.dim() == 1:
      batch_ctx_ids = batch_ctx_ids.unsqueeze(0)
  if batch_ctx_mask.dim() == 1:
      batch_ctx_mask = batch_ctx_mask.unsqueeze(0)

  batch_inputs["attention_mask"] = batch_inputs["attention_mask"].long()
  assert batch_inputs["input_ids"].shape == batch_inputs["attention_mask"].shape
  assert batch_ctx_ids.shape == batch_ctx_mask.shape

  return batch_inputs, batch_ctx_ids, batch_ctx_mask

# Load GLiNER
model = GLiNERRagCrossAttn("urchade/gliner_large-v1").to(DEVICE)

# Checks always that the gliner parameters are frozen and only the cross-attention is trained. Else, stop script.
assert not any(p.requires_grad for p in model.gliner.parameters())

# Instatiating collator as the object of the class, data_collator_class
# Set prepare_labels=True for training so the collator builds label tensors
# while assembling sample dicts into a model-ready batch.
collator = model.gliner.data_collator_class(
    model.gliner.config, data_processor=model.gliner.data_processor, prepare_labels=True
)

import time

criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.AdamW(model.context_cross_attn.parameters(), lr=1e-4)

# --- 4. Epoch-Based Train & Validate Loop ---
save_dir = Path("models")
save_dir.mkdir(exist_ok=True)
save_path = save_dir/"cross_attn_best.pt"

best_val_loss = float('inf') # Track the best loss

# Start training proper
for epoch in range(1, EPOCHS+1):

    start_time = time.time()

    train_loss, train_acc = fn_train_batch (model, collator, train_data, train_data_rag, BATCH_SIZE, optimizer, criterion)
    val_loss, val_acc = fn_eval_batch (model, collator, train_data, train_data_rag, BATCH_SIZE, optimizer, criterion)

    epoch_mins, epoch_secs = epoch_time(start_time, end_time)

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.context_cross_attn.state_dict(), save_path)

    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')

print(f"\nTraining complete. Best model weights saved to {save_path}")

# model.context_cross_attn.load_state_dict(torch.load(save_path))

# test_loss, test_acc = fn_eval_batch (model, collator, test_data, test_data_rag, BATCH_SIZE, optimizer, criterion)

# print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc*100:.2f}%')

# print(f"Epoch {epoch}/{EPOCHS} | Train Loss: {avg_train_loss:.4f} | Validation Loss: {avg_val_loss:.4f}")
# # CHECKPOINTING
#     if avg_val_loss < best_val_loss:
#         best_val_loss = avg_val_loss
#         torch.save(model.context_cross_attn.state_dict(), save_path)

#     print("-" * 40)

# print(f"\nTraining complete. Best model weights saved to {save_path}")