# -*- coding: utf-8 -*-
"""build_AI_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXIcotPdlqRkUQGmx-cWYUdpvh5Sy9El

AI Corpora
Here are the 2 corpora I used to build the AI knowledge base.

arXiv abstracts from cs.AI, cs.CL, and cs.LG
Natural language text covering algorithms, tasks, fields, metrics, products and researchers
Seems like should be well aligned with most of the CrossNER-AI labels
DBLP metadata
For conference, journal and researcher coverage
arXiv abstracts may not contain this info
I noticed the label space of the CrossNER AI subset is oddly specific (conference, field, metrics, product, programlang, researcher, task etc), in that it doesn't include true AI/ML domain knowledge - for example, the kind of knowledge that we're studying in our NTU MSAI. Hence I feel the corpora should be deliberately biased toward research papers, benchmarks and scholarly metadata.

I wanted to include Papers with Code also, but the code keeps breaking despite repeatedly trying to fix it with ChatGPT, Gemini etc. Major problem is there's no direct API to scrape from. In the end I decided to abandon it completely, I think the arXiv abstracts and DBLP metadata should be good enough.

Total: about 57.0k documents in 59.9k chunks
"""

def build_ai_rag_corpus(output_dir="ai_rag"):
    """
    Build a RAG-ready AI corpus targeted to CrossNER's 'ai' subset from:
      1) arXiv (cs.AI / cs.CL / cs.LG), harvested in date windows
         to avoid unstable deep-offset pagination
      2) DBLP

    Outputs:
      - arxiv.jsonl
      - dblp.jsonl
      - ai_rag_corpus.jsonl
      - ai_rag_corpus_chunked.jsonl
    """

    import os
    import re
    import json
    import html
    import time
    import calendar
    import requests
    import xml.etree.ElementTree as ET
    from datetime import datetime

    os.makedirs(output_dir, exist_ok=True)

    session = requests.Session()
    session.headers.update({"User-Agent": "Mozilla/5.0 ai-rag-builder/1.0"})

    def clean_text(text):
        if text is None:
            return ""
        text = html.unescape(str(text))
        text = re.sub(r"\s+", " ", text).strip()
        return text

    def write_jsonl(records, path):
        with open(path, "w", encoding="utf-8") as f:
            for r in records:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")

    def chunk_text(text, size=200, overlap=40):
        words = text.split()
        if not words:
            return []
        step = max(1, size - overlap)
        chunks = []
        for i in range(0, len(words), step):
            chunk = " ".join(words[i:i + size]).strip()
            if len(chunk.split()) > 20:
                chunks.append(chunk)
            if i + size >= len(words):
                break
        return chunks

    def yyyymmddtttt(year, month, day, hour=0, minute=0):
        return f"{year:04d}{month:02d}{day:02d}{hour:02d}{minute:02d}"

    def month_start_end_strings(year, month):
        last_day = calendar.monthrange(year, month)[1]
        start = yyyymmddtttt(year, month, 1, 0, 0)
        end = yyyymmddtttt(year, month, last_day, 23, 59)
        return start, end

    def iter_month_windows(start_year=2015, end_year=None):
        """
        Yield month windows from newest to oldest.
        """
        if end_year is None:
            end_year = datetime.utcnow().year

        windows = []
        for year in range(end_year, start_year - 1, -1):
            start_month = 12
            end_month = 1
            for month in range(start_month, end_month - 1, -1):
                s, e = month_start_end_strings(year, month)
                windows.append((year, month, s, e))
        return windows

    def get_arxiv_feed_root(url, max_retries=5, timeout=120):
        last_err = None
        for attempt in range(max_retries):
            try:
                r = session.get(url, timeout=timeout)
                r.raise_for_status()
                return ET.fromstring(r.text)
            except Exception as e:
                last_err = e
                sleep_s = min(60, 2 ** attempt)
                print(f"[WARN] arXiv request failed, retry {attempt+1}/{max_retries}: {e}")
                time.sleep(sleep_s)
        raise RuntimeError(f"arXiv request failed after retries: {last_err}")

    all_records = []

    # ------------------------------------------------------------------
    # 1) arXiv
    # ------------------------------------------------------------------
    def fetch_arxiv_month_records(category, start_date, end_date, max_pages=20, batch_size=500):
        """
        Fetch one category within one month window.
        Keeps offsets low by construction.
        """
        base = "http://export.arxiv.org/api/query"
        query = f"cat:{category}+AND+submittedDate:[{start_date}+TO+{end_date}]"

        ns = {
            "atom": "http://www.w3.org/2005/Atom",
            "opensearch": "http://a9.com/-/spec/opensearch/1.1/",
        }

        # Probe the window first
        probe_url = (
            f"{base}?search_query={query}"
            f"&start=0&max_results=1"
            f"&sortBy=submittedDate&sortOrder=descending"
        )
        probe_root = get_arxiv_feed_root(probe_url, max_retries=5, timeout=120)
        total_text = probe_root.findtext("opensearch:totalResults", default="0", namespaces=ns)
        total_results = int(total_text) if str(total_text).isdigit() else 0

        if total_results == 0:
            return [], total_results

        if total_results > max_pages * batch_size:
            print(
                f"[WARN] arXiv window too large for {category} {start_date}-{end_date}: "
                f"totalResults={total_results}. Skipping this window to avoid deep offsets."
            )
            return [], total_results

        records = []
        seen_ids = set()

        for start in range(0, total_results, batch_size):
            url = (
                f"{base}?search_query={query}"
                f"&start={start}&max_results={batch_size}"
                f"&sortBy=submittedDate&sortOrder=descending"
            )
            root = get_arxiv_feed_root(url, max_retries=5, timeout=120)
            entries = root.findall("atom:entry", ns)
            if not entries:
                break

            for entry in entries:
                raw_id = clean_text(entry.findtext("atom:id", default="", namespaces=ns))
                arxiv_id = raw_id.rsplit("/", 1)[-1] if raw_id else ""

                if arxiv_id and arxiv_id in seen_ids:
                    continue
                if arxiv_id:
                    seen_ids.add(arxiv_id)

                title = clean_text(entry.findtext("atom:title", default="", namespaces=ns))
                summary = clean_text(entry.findtext("atom:summary", default="", namespaces=ns))
                published = clean_text(entry.findtext("atom:published", default="", namespaces=ns))
                updated = clean_text(entry.findtext("atom:updated", default="", namespaces=ns))

                authors = []
                for a in entry.findall("atom:author", ns):
                    name = clean_text(a.findtext("atom:name", default="", namespaces=ns))
                    if name:
                        authors.append(name)

                categories = []
                for c in entry.findall("atom:category", ns):
                    term = clean_text(c.attrib.get("term", ""))
                    if term:
                        categories.append(term)

                text_parts = []
                if summary:
                    text_parts.append(summary)
                if authors:
                    text_parts.append("Authors: " + "; ".join(authors[:15]))
                if categories:
                    text_parts.append("Categories: " + "; ".join(sorted(set(categories))[:10]))

                if title and text_parts:
                    records.append({
                        "source": "arXiv",
                        "title": title,
                        "text": clean_text(" ".join(text_parts)),
                        "meta": {
                            "arxiv_id": arxiv_id,
                            "published": published,
                            "updated": updated,
                            "authors": authors[:25],
                            "categories": sorted(set(categories)),
                            "window_start": start_date,
                            "window_end": end_date,
                        }
                    })

            time.sleep(3)

        return records, total_results

    print("Downloading arXiv AI records ...")
    arxiv_categories = ["cs.AI", "cs.CL", "cs.LG"]
    print("arXiv categories:", arxiv_categories)

    arxiv_records = []
    seen_arxiv = set()

    # Rough target near biomedical scale while avoiding deep arXiv offsets
    arxiv_caps = {
        "cs.AI": 12000,
        "cs.CL": 12000,
        "cs.LG": 12000,
    }

    # Monthly windows from newest backwards; adjust start_year if needed
    windows = iter_month_windows(start_year=2015, end_year=datetime.utcnow().year)

    for cat in arxiv_categories:
        collected = 0
        for year, month, start_date, end_date in windows:
            if collected >= arxiv_caps[cat]:
                break

            recs, total_results = fetch_arxiv_month_records(
                category=cat,
                start_date=start_date,
                end_date=end_date,
                max_pages=20,
                batch_size=500,
            )

            if total_results > 0:
                print(
                    f"arXiv {cat} {year}-{month:02d}: totalResults={total_results}, "
                    f"kept={len(recs)}"
                )

            for r in recs:
                arxiv_id = r.get("meta", {}).get("arxiv_id", "")
                key = arxiv_id or (r["title"], tuple(r.get("meta", {}).get("authors", [])[:3]))
                if key not in seen_arxiv:
                    seen_arxiv.add(key)
                    arxiv_records.append(r)
                    collected += 1
                    if collected >= arxiv_caps[cat]:
                        break

    write_jsonl(arxiv_records, os.path.join(output_dir, "arxiv.jsonl"))
    all_records.extend(arxiv_records)

    # ------------------------------------------------------------------
    # 2) DBLP
    # ------------------------------------------------------------------
    def fetch_dblp_records(query, max_hits=1500):
        """
        Pull publication metadata from DBLP search API.
        """
        base = "https://dblp.org/search/publ/api"
        offset = 0
        page_size = 1000
        records = []

        while offset < max_hits:
            h = min(page_size, max_hits - offset)
            url = f"{base}?q={query}&format=json&h={h}&f={offset}"
            r = session.get(url, timeout=60)
            r.raise_for_status()
            data = r.json()

            hits = data.get("result", {}).get("hits", {}).get("hit", [])
            if not hits:
                break

            for hit in hits:
                info = hit.get("info", {})

                title = clean_text(info.get("title", ""))
                venue = clean_text(info.get("venue", ""))
                year = clean_text(info.get("year", ""))
                typ = clean_text(info.get("type", ""))

                authors = []
                authors_raw = info.get("authors", {}).get("author", [])
                if isinstance(authors_raw, dict):
                    authors_raw = [authors_raw]

                for a in authors_raw:
                    if isinstance(a, dict):
                        name = clean_text(a.get("text", ""))
                    else:
                        name = clean_text(a)
                    if name:
                        authors.append(name)

                text_parts = []
                if venue:
                    text_parts.append(f"Venue: {venue}")
                if year:
                    text_parts.append(f"Year: {year}")
                if typ:
                    text_parts.append(f"Type: {typ}")
                if authors:
                    text_parts.append("Authors: " + "; ".join(authors[:15]))

                if title and text_parts:
                    records.append({
                        "source": "DBLP",
                        "title": title,
                        "text": clean_text(" ".join(text_parts)),
                        "meta": {
                            "venue": venue,
                            "year": year,
                            "type": typ,
                            "authors": authors[:25],
                        }
                    })

            offset += len(hits)
            if len(hits) < h:
                break

            time.sleep(1)

        return records

    dblp_queries = [
        "NeurIPS", "ICML", "ICLR", "AAAI", "IJCAI",
        "ACL", "EMNLP", "NAACL", "COLING", "JMLR",
        "AISTATS", "UAI", "CVPR", "ECCV", "ICCV"
    ]

    dblp_records = []
    seen = set()

    print("Downloading DBLP AI records ...")
    print("DBLP queries:", dblp_queries)

    for q in dblp_queries:
        try:
            recs = fetch_dblp_records(q, max_hits=1500)
            for r in recs:
                key = (r["title"], r["meta"].get("venue", ""), r["meta"].get("year", ""))
                if key not in seen:
                    seen.add(key)
                    dblp_records.append(r)
        except Exception as e:
            print(f"[WARN] DBLP query failed for {q}: {e}")

    write_jsonl(dblp_records, os.path.join(output_dir, "dblp.jsonl"))
    all_records.extend(dblp_records)

    # ------------------------------------------------------------------
    # 3) Merge corpus
    # ------------------------------------------------------------------
    merged = os.path.join(output_dir, "ai_rag_corpus.jsonl")
    write_jsonl(all_records, merged)

    # ------------------------------------------------------------------
    # 4) Chunk corpus
    # ------------------------------------------------------------------
    chunk_file = os.path.join(output_dir, "ai_rag_corpus_chunked.jsonl")
    chunks = []

    for i, doc in enumerate(all_records):
        for j, c in enumerate(chunk_text(doc["text"])):
            chunks.append({
                "doc_id": i,
                "chunk_id": f"{i}_{j}",
                "source": doc["source"],
                "title": doc["title"],
                "text": c,
                "meta": doc.get("meta", {})
            })

    write_jsonl(chunks, chunk_file)

    return {
        "documents": len(all_records),
        "chunks": len(chunks),
        "n_arxiv": len(arxiv_records),
        "n_dblp": len(dblp_records),
        "arxiv_jsonl": os.path.join(output_dir, "arxiv.jsonl"),
        "dblp_jsonl": os.path.join(output_dir, "dblp.jsonl"),
        "merged_jsonl": merged,
        "chunked_jsonl": chunk_file,
        "output_dir": output_dir,
    }

# Test case -- this works as of 5 Apr 2026 (Wilbert)

result = build_ai_rag_corpus("ai_rag")
print(result)

"""Build AI Vector Store"""

!pip install chromadb sentence-transformers

import os
import json
import chromadb
from chromadb.utils import embedding_functions
from tqdm import tqdm

def create_ai_vector_store(
    jsonl_path="ai_rag/ai_rag_corpus_chunked.jsonl",
    persist_directory="ai_vector_store"
):
    """
    Reads the chunked AI corpus and builds a ChromaDB vector store
    using the all-MiniLM-L6-v2 embedding model.
    """

    if not os.path.exists(jsonl_path):
        raise FileNotFoundError(f"Cannot find {jsonl_path}. Did Wilbert's script finish running?")

    print(f"Initializing ChromaDB persistent client at ./{persist_directory}")
    client = chromadb.PersistentClient(path=persist_directory)

    print("Loading all-MiniLM-L6-v2 embedding function...")
    sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name="all-MiniLM-L6-v2"
    )

    # Create or get the collection
    collection = client.get_or_create_collection(
        name="ai_knowledge_base",
        embedding_function=sentence_transformer_ef,
        metadata={"description": "CrossNER AI subset RAG corpus (arXiv & DBLP)"}
    )

    documents = []
    metadatas = []
    ids = []

    print("Reading and flattening JSONL records...")
    with open(jsonl_path, 'r', encoding='utf-8') as f:
        for line in f:
            record = json.loads(line)

            chunk_id = record["chunk_id"]
            text = record["text"]

            # Flatten metadata for ChromaDB compatibility
            meta = record.get("meta", {})
            flat_meta = {
                "source": record.get("source", "Unknown"),
                "title": record.get("title", "Untitled")
            }

            # Convert lists to comma-separated strings
            if "authors" in meta and isinstance(meta["authors"], list):
                flat_meta["authors"] = ", ".join(meta["authors"])
            if "categories" in meta and isinstance(meta["categories"], list):
                flat_meta["categories"] = ", ".join(meta["categories"])

            # Grab DBLP specific meta if it exists
            if "venue" in meta:
                flat_meta["venue"] = str(meta["venue"])
            if "year" in meta:
                flat_meta["year"] = str(meta["year"])
            if "type" in meta:
                flat_meta["type"] = str(meta["type"])

            # Grab arXiv specific meta if it exists
            if "arxiv_id" in meta:
                flat_meta["arxiv_id"] = str(meta["arxiv_id"])

            documents.append(text)
            metadatas.append(flat_meta)
            ids.append(chunk_id)

    total_chunks = len(ids)
    print(f"Found {total_chunks} chunks. Beginning embedding and database insertion...")


    batch_size = 5461

    for i in tqdm(range(0, total_chunks, batch_size), desc="Uploading to Chroma"):
        end_idx = min(i + batch_size, total_chunks)
        collection.add(
            documents=documents[i:end_idx],
            metadatas=metadatas[i:end_idx],
            ids=ids[i:end_idx]
        )

    print(f"\nSuccess! AI Vector Store built at ./{persist_directory}")

if __name__ == "__main__":
    create_ai_vector_store()

"""Push to Google Drive"""

'''import shutil
import os
from google.colab import drive

# 1. Mount your Google Drive to the Colab environment
# This will prompt a popup asking for permission to access your Drive
drive.mount('/content/drive')

# 2. Define the local Colab source and the Google Drive destination
source_folder = "ai_vector_store"
destination_folder = "/content/drive/MyDrive/NLP_Project/ai_vector_store"

# 3. Copy the database folder to Google Drive
if not os.path.exists(source_folder):
    print(f"Error: {source_folder} not found. Did the ChromaDB build finish?")
else:
    print(f"Transferring {source_folder} to {destination_folder}...")
    # dirs_exist_ok=True allows it to overwrite/update if you run this multiple times
    shutil.copytree(source_folder, destination_folder, dirs_exist_ok=True)
    print("Successfully pushed to Google Drive /NLP_Project!")'''

"""Push .jsonl to Drive"""

'''import shutil
import os
from google.colab import drive

# 1. Mount Drive
drive.mount('/content/drive')

# 2. Define paths
ai_source = "ai_rag"
ai_dest = "/content/drive/MyDrive/NLP_Project/ai_rag_data"

# 3. Push the AI data
if os.path.exists(ai_source):
    print(f"Transferring {ai_source} to {ai_dest}...")
    shutil.copytree(ai_source, ai_dest, dirs_exist_ok=True)
    print("✅ AI JSONL files successfully backed up to your shared Drive!")
else:
    print(f"⚠️ Error: {ai_source} folder not found. Did the cells above finish running?")'''