# -*- coding: utf-8 -*-
"""gliner_build_db_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnFHBCFeUgNPMCtZb7cbKxKl9V_lrb9D

# Test Set: Movie Corpora

MIT Movie Trivia dataset: https://huggingface.co/datasets/tner/mit_movie_trivia
- Unfortunately I can't find the detailed methodology used to build this dataset, so I don't know exactly which corpora were used.
- But it looks like movies can date all the way back to 1950s

But I think it's reasonable for us to use these:
1. Wikipedia movie plots (Hugging Face: vishnupriyavr/wiki-movie-plots-with-summaries) - year 1901-2017
2. Movie descriptors (Hugging Face: mt0rm0/movie_descriptors) - year up to 2017
3. Cornell movie dialogs (Hugging Faec: spawn99/CornellMovieDialogCorpus)

In theory IMDb is an ideal corpus, but I realised the non-commercial downloadable files are metadata rather than a plot summary corpus... not sure how rich a dataset this will be. Chose not to use it.

Rotten tomatoes is difficult to scrape, so I didn't use it.
"""

def build_movie_rag_corpus(
    output_dir="movie_rag",
    wiki_limit=25000,
    descriptors_limit=35000,
    cornell_limit=15000,
):
    """
    Build a RAG-ready movie-domain corpus from:
      1) Wikipedia Movie Plots
      2) Movie Descriptors
      3) Cornell Movie Dialogs (Parquet-backed Hugging Face dataset)

    Outputs:
      - wikipedia_movie_plots.jsonl
      - movie_descriptors.jsonl
      - cornell_movie_dialogs.jsonl
      - movie_rag_corpus.jsonl
      - movie_rag_corpus_chunked.jsonl
    """

    import os
    import re
    import json

    try:
        from datasets import load_dataset
    except ImportError as e:
        raise ImportError(
            "This function requires the 'datasets' package. Install it with: pip install datasets"
        ) from e

    os.makedirs(output_dir, exist_ok=True)

    def clean_text(text):
        if text is None:
            return ""
        return re.sub(r"\s+", " ", str(text)).strip()

    def write_jsonl(records, path):
        with open(path, "w", encoding="utf-8") as f:
            for r in records:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")

    def chunk_text(text, size=200, overlap=40):
        words = text.split()
        if not words:
            return []
        step = max(1, size - overlap)
        chunks = []
        for i in range(0, len(words), step):
            chunk = " ".join(words[i:i + size]).strip()
            if len(chunk.split()) > 20:
                chunks.append(chunk)
            if i + size >= len(words):
                break
        return chunks

    all_records = []

    # ------------------------------------------------------------------
    # 1) Wikipedia Movie Plots
    # ------------------------------------------------------------------
    print("Loading Wikipedia Movie Plots from Hugging Face ...")
    wiki_ds = load_dataset("vishnupriyavr/wiki-movie-plots-with-summaries", split="train")

    wiki_records = []
    for idx, row in enumerate(wiki_ds):
        if wiki_limit is not None and idx >= wiki_limit:
            break

        title = clean_text(row.get("Title"))
        year = row.get("Release Year")
        origin = clean_text(row.get("Origin/Ethnicity"))
        director = clean_text(row.get("Director"))
        cast = clean_text(row.get("Cast"))
        genre = clean_text(row.get("Genre"))
        wiki_page = clean_text(row.get("Wiki Page"))
        plot = clean_text(row.get("Plot"))
        plot_summary = clean_text(row.get("PlotSummary"))

        if not title:
            continue

        text_parts = [title]
        if year:
            text_parts.append(f"Year: {year}")
        if origin:
            text_parts.append(f"Origin: {origin}")
        if director and director.lower() != "unknown":
            text_parts.append(f"Director: {director}")
        if cast and cast.lower() not in {"unknown", "null"}:
            text_parts.append(f"Cast: {cast}")
        if genre and genre.lower() != "unknown":
            text_parts.append(f"Genre: {genre}")
        if plot_summary:
            text_parts.append(f"Plot summary: {plot_summary}")
        elif plot:
            text_parts.append(f"Plot: {plot}")

        wiki_records.append({
            "source": "WikipediaMoviePlots",
            "title": title,
            "text": clean_text(" ".join(text_parts)),
            "meta": {
                "year": year,
                "origin": origin,
                "director": director,
                "genre": genre,
                "wiki_page": wiki_page,
            }
        })

    write_jsonl(wiki_records, os.path.join(output_dir, "wikipedia_movie_plots.jsonl"))
    all_records.extend(wiki_records)

    # ------------------------------------------------------------------
    # 2) Movie Descriptors
    # ------------------------------------------------------------------
    print("Loading Movie Descriptors from Hugging Face ...")
    desc_ds = load_dataset("mt0rm0/movie_descriptors", split="train")

    descriptor_records = []
    for idx, row in enumerate(desc_ds):
        if descriptors_limit is not None and idx >= descriptors_limit:
            break

        title = clean_text(row.get("name"))
        year = row.get("release_year")
        overview = clean_text(row.get("overview"))

        if not title or not overview:
            continue

        text_parts = [title]
        if year:
            text_parts.append(f"Year: {year}")
        text_parts.append(f"Overview: {overview}")

        descriptor_records.append({
            "source": "MovieDescriptors",
            "title": title,
            "text": clean_text(" ".join(text_parts)),
            "meta": {
                "release_year": year,
            }
        })

    write_jsonl(descriptor_records, os.path.join(output_dir, "movie_descriptors.jsonl"))
    all_records.extend(descriptor_records)

    # ------------------------------------------------------------------
    # 3) Cornell Movie Dialogs (Parquet-backed replacement)
    # ------------------------------------------------------------------
    print("Loading Cornell Movie Dialogs from Hugging Face ...")
    cornell_ds = load_dataset("spawn99/CornellMovieDialogCorpus", split="movie_lines")

    cornell_records = []
    for idx, row in enumerate(cornell_ds):
        if cornell_limit is not None and idx >= cornell_limit:
            break

        # Defensive field handling
        movie_title = clean_text(
            row.get("movieTitle")
            or row.get("movie_title")
            or row.get("title")
            or row.get("movie")
        )
        movie_year = clean_text(
            row.get("movieYear")
            or row.get("movie_year")
            or row.get("year")
        )
        character_name = clean_text(
            row.get("characterName")
            or row.get("character_name")
            or row.get("speaker")
            or row.get("character")
        )
        text = clean_text(
            row.get("text")
            or row.get("line")
            or row.get("utterance")
            or row.get("dialogue")
        )
        movie_id = clean_text(
            row.get("movieID")
            or row.get("movie_id")
            or row.get("movieId")
        )
        character_id = clean_text(
            row.get("characterID")
            or row.get("character_id")
            or row.get("characterId")
        )

        if not text:
            continue

        title = movie_title or f"CornellMovie {movie_id or idx}"

        text_parts = []
        if movie_title:
            text_parts.append(f"Movie: {movie_title}")
        if movie_year:
            text_parts.append(f"Year: {movie_year}")
        if character_name:
            text_parts.append(f"Character: {character_name}")
        text_parts.append(f"Dialogue: {text}")

        cornell_records.append({
            "source": "CornellMovieDialogs",
            "title": title,
            "text": clean_text(" ".join(text_parts)),
            "meta": {
                "movie_id": movie_id,
                "movie_year": movie_year,
                "character_id": character_id,
                "character_name": character_name,
            }
        })

    write_jsonl(cornell_records, os.path.join(output_dir, "cornell_movie_dialogs.jsonl"))
    all_records.extend(cornell_records)

    # ------------------------------------------------------------------
    # 4) Merge corpus
    # ------------------------------------------------------------------
    merged = os.path.join(output_dir, "movie_rag_corpus.jsonl")
    write_jsonl(all_records, merged)

    # ------------------------------------------------------------------
    # 5) Chunk corpus
    # ------------------------------------------------------------------
    chunk_file = os.path.join(output_dir, "movie_rag_corpus_chunked.jsonl")
    chunks = []

    for i, doc in enumerate(all_records):
        for j, c in enumerate(chunk_text(doc["text"])):
            chunks.append({
                "doc_id": i,
                "chunk_id": f"{i}_{j}",
                "source": doc["source"],
                "title": doc["title"],
                "text": c,
                "meta": doc.get("meta", {})
            })

    write_jsonl(chunks, chunk_file)

    return {
        "documents": len(all_records),
        "chunks": len(chunks),
        "n_wikipedia_movie_plots": len(wiki_records),
        "n_movie_descriptors": len(descriptor_records),
        "n_cornell_movie_dialogs": len(cornell_records),
        "wikipedia_movie_plots_jsonl": os.path.join(output_dir, "wikipedia_movie_plots.jsonl"),
        "movie_descriptors_jsonl": os.path.join(output_dir, "movie_descriptors.jsonl"),
        "cornell_movie_dialogs_jsonl": os.path.join(output_dir, "cornell_movie_dialogs.jsonl"),
        "merged_jsonl": merged,
        "chunked_jsonl": chunk_file,
        "output_dir": output_dir,
    }

result = build_movie_rag_corpus(
    "movie_rag",
    wiki_limit=25000,
    descriptors_limit=35000,
    cornell_limit=15000,
)
print(result)

#!pip install chromadb sentence-transformers

import os
import json
import chromadb
from chromadb.utils import embedding_functions
from tqdm import tqdm

# Setup temporary local database path
#DB_PATH = "/content/local_movie_vector_store/"

# The offline movie corpus
MOVIE_PATH = "/content/movie_rag/movie_rag_corpus_chunked.jsonl"

def process_movie_corpus(file_path, limit=None):
    """Loads pre-chunked movie JSONL dataset and safely formats metadata."""
    print(f"Loading movie corpus from {file_path}...")
    docs, metadatas, ids = [], [], []

    if not os.path.exists(file_path):
        print(f"Warning: File not found at {file_path}.")
        return docs, metadatas, ids

    with open(file_path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            if limit and i >= limit:
                break

            row = json.loads(line)

            docs.append(row["text"])

            meta_dict = {
                "source": row.get("source", "unknown"),
                "title": str(row.get("title", ""))[:100]
            }

            for k, v in row.get("meta", {}).items():
                meta_dict[k] = str(v)

            metadatas.append(meta_dict)

            prefix = row.get("source", "doc").replace("/", "_").replace(" ", "")
            chunk_id = row.get("chunk_id", f"chk_{i}")
            ids.append(f"{prefix}_{chunk_id}")

    return docs, metadatas, ids

def build_movie_vector_store(testing_mode=False):
    print("Initializing ChromaDB client for Movie Domain...")
    client = chromadb.PersistentClient(path=DB_PATH)

    sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name="all-MiniLM-L6-v2"
    )

    # Creating collection for movies
    collection = client.get_or_create_collection(
        name="movie_knowledge_base",
        embedding_function=sentence_transformer_ef,
        metadata={"hnsw:space": "cosine"}
    )

    jsonl_limit = 500 if testing_mode else None

    # Load Movie Database
    all_docs, all_metadatas, all_ids = process_movie_corpus(MOVIE_PATH, limit=jsonl_limit)

    batch_size = 5000
    total_docs = len(all_docs)
    print(f"\nTotal movie documents ready for ingestion: {total_docs}")

    if total_docs == 0:
        print("No documents loaded!")
        return

    print("Embedding and adding to ChromaDB...")

    for idx in tqdm(range(0, total_docs, batch_size), desc="Ingesting Movie Batches"):
        end_idx = min(idx + batch_size, total_docs)
        collection.add(
            documents=all_docs[idx:end_idx],
            metadatas=all_metadatas[idx:end_idx],
            ids=all_ids[idx:end_idx]
        )

    print(f"\nSuccess! Full offline movie vector database compiled at {DB_PATH}")

# Ensure this is False to build the full 27,501 chunk database
  build_movie_vector_store(testing_mode=False)

#Connect to Google Drive
#from google.colab import drive
#drive.mount('/content/drive')

# Create the new folder
#!mkdir -p "/content/drive/MyDrive/NLP_Project/movie_vector_store/"

# Copy the completed local database over
#!cp -r /content/local_movie_vector_store/* "/content/drive/MyDrive/NLP_Project/movie_vector_store/"

print("Successfully copied Movie Database to Google Drive!")