# -*- coding: utf-8 -*-
"""build_politics_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hy4ljHl-7sZffZ09qg8Hb3fGizX-pes3

Politics Corpora
These 2 corpora were used for the politics knowledge base:

Miller Center speeches
Presidential speeches collection
Europarl
Large-scale parliamentary text
CrossNER’s politics subset is centered on entities such as political parties, politicians, elections, and countries. So a practical politics RAG builder should bias toward encyclopedic political entities and official country coverage rather than generic news text.

Note: I initially wanted to scrape Wikipedia. But Wiki throws 429 ("Too Many Requests") errors when crawled, hence it can't be crawled effectively as the primary corpus. So I abandoned this idea.

Total: about 32.0k documents in 114.8k chunks
"""

def build_politics_rag_corpus(output_dir="politics_rag"):
    import os
    import re
    import io
    import json
    import html
    import time
    import tarfile
    from urllib.parse import urljoin

    import requests
    from bs4 import BeautifulSoup

    os.makedirs(output_dir, exist_ok=True)

    session = requests.Session()
    session.headers.update({
        "User-Agent": "rag-builder/1.0"
    })

    def clean(text):
        if text is None:
            return ""
        return re.sub(r"\s+", " ", html.unescape(str(text))).strip()

    def write_jsonl(data, path):
        with open(path, "w", encoding="utf-8") as f:
            for d in data:
                f.write(json.dumps(d, ensure_ascii=False) + "\n")

    def chunk_text(text, size=200, overlap=40):
        words = text.split()
        if not words:
            return []
        step = max(1, size - overlap)
        chunks = []
        for i in range(0, len(words), step):
            chunk = " ".join(words[i:i + size]).strip()
            if len(chunk.split()) > 20:
                chunks.append(chunk)
            if i + size >= len(words):
                break
        return chunks

    def fmt_bytes(n):
        for unit in ["B", "KB", "MB", "GB", "TB"]:
            if n < 1024 or unit == "TB":
                return f"{n:.1f}{unit}" if unit != "B" else f"{int(n)}B"
            n /= 1024.0

    def safe_get(url, stream=False, timeout=120, max_retries=5):
        last_err = None
        for i in range(max_retries):
            try:
                r = session.get(url, timeout=timeout, stream=stream)
                r.raise_for_status()
                return r
            except Exception as e:
                last_err = e
                wait = 2 ** i
                print(f"[WARN] retry {i+1}/{max_retries}: {e}")
                time.sleep(wait)
        raise RuntimeError(f"Download failed: {last_err}")

    def download_with_progress(url, path, timeout=300):
        r = safe_get(url, stream=True, timeout=timeout)
        total = int(r.headers.get("Content-Length", 0))
        downloaded = 0
        chunk_size = 1024 * 1024
        start = time.time()
        last_print = start

        print(f"Starting download: {url}")
        if total:
            print(f"Expected size: {fmt_bytes(total)}")

        with open(path, "wb") as f:
            for chunk in r.iter_content(chunk_size):
                if not chunk:
                    continue
                f.write(chunk)
                downloaded += len(chunk)

                now = time.time()
                if now - last_print >= 2:
                    elapsed = now - start
                    speed = downloaded / elapsed if elapsed > 0 else 0
                    if total:
                        pct = 100 * downloaded / total
                        print(
                            f"Downloaded {fmt_bytes(downloaded)} / {fmt_bytes(total)} "
                            f"({pct:.1f}%) at {fmt_bytes(speed)}/s"
                        )
                    else:
                        print(f"Downloaded {fmt_bytes(downloaded)} at {fmt_bytes(speed)}/s")
                    last_print = now

        elapsed = time.time() - start
        print(f"Finished download: {path} in {elapsed:.1f}s")

    def add_doc(docs, seen, source, title, text, meta=None):
        title = clean(title)
        text = clean(text)
        if not title or not text:
            return
        key = (source, title, text[:200])
        if key in seen:
            return
        seen.add(key)
        docs.append({
            "source": source,
            "title": title,
            "text": text,
            "meta": meta or {}
        })

    all_docs = []

    # =========================================================
    # 1) MILLER CENTER PRESIDENTIAL SPEECHES
    # =========================================================
    print("Scraping Miller Center presidential speeches...")
    speeches_index_url = "https://millercenter.org/the-presidency/presidential-speeches"

    def collect_miller_speech_links(index_url):
        r = safe_get(index_url, timeout=120)
        soup = BeautifulSoup(r.text, "html.parser")

        links = []
        seen = set()

        for a in soup.find_all("a", href=True):
            href = a["href"].strip()
            full = urljoin(index_url, href)
            # Filter to speech pages
            if "/the-presidency/presidential-speeches/" in full:
                # exclude listing page itself
                if full.rstrip("/") == index_url.rstrip("/"):
                    continue
                if full not in seen:
                    seen.add(full)
                    links.append(full)

        return links

    def parse_miller_speech_page(url):
        r = safe_get(url, timeout=120)
        soup = BeautifulSoup(r.text, "html.parser")

        title = ""
        h1 = soup.find("h1")
        if h1:
            title = clean(h1.get_text(" ", strip=True))

        # Collect substantial paragraphs from main/article region
        text_blocks = []

        candidates = soup.find_all(["div", "section", "article"])
        for c in candidates:
            cls = " ".join(c.get("class", []))
            ident = c.get("id", "")
            marker = f"{cls} {ident}".lower()
            if any(k in marker for k in ["speech", "transcript", "body", "content", "main"]):
                paras = c.find_all("p")
                local_text = " ".join(clean(p.get_text(" ", strip=True)) for p in paras)
                local_text = clean(local_text)
                if len(local_text.split()) > 80:
                    text_blocks.append(local_text)

        # Fallback: use all paragraphs on page
        if not text_blocks:
            paras = soup.find_all("p")
            fallback = " ".join(clean(p.get_text(" ", strip=True)) for p in paras)
            fallback = clean(fallback)
            if len(fallback.split()) > 80:
                text_blocks.append(fallback)

        text = max(text_blocks, key=lambda x: len(x.split()), default="")

        # Try extracting president + date if present
        meta = {"url": url}
        page_text = soup.get_text(" ", strip=True)
        page_text = clean(page_text)

        m = re.search(r"([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)\s+Presidency", page_text)
        if m:
            meta["president"] = m.group(1)

        m2 = re.search(
            r"(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+\d{4}",
            page_text
        )
        if m2:
            meta["date"] = m2.group(0)

        return title, text, meta

    miller_docs = []
    miller_seen = set()

    try:
        speech_links = collect_miller_speech_links(speeches_index_url)
        print(f"Miller Center speech links found: {len(speech_links)}")
    except Exception as e:
        print(f"[WARN] Could not collect Miller Center speech links: {e}")
        speech_links = []

    for idx, link in enumerate(speech_links, start=1):
        if idx % 25 == 0 or idx == 1:
            print(f"Miller Center pages parsed: {idx-1}/{len(speech_links)} | docs kept: {len(miller_docs)}")

        try:
            title, text, meta = parse_miller_speech_page(link)
            if len(text.split()) >= 80:
                add_doc(miller_docs, miller_seen, "MillerCenter", title or link.rsplit("/", 1)[-1], text, meta)
        except Exception as e:
            print(f"[WARN] Failed Miller Center page: {link} | {e}")

    print(f"Miller Center documents: {len(miller_docs)}")
    miller_path = f"{output_dir}/millercenter.jsonl"
    write_jsonl(miller_docs, miller_path)
    all_docs.extend(miller_docs)

    # =========================================================
    # 2) EUROPARL
    # =========================================================
    print("Downloading Europarl...")
    euro_url = "https://www.statmt.org/europarl/v7/europarl.tgz"
    euro_file = f"{output_dir}/europarl.tgz"

    if not os.path.exists(euro_file):
        download_with_progress(euro_url, euro_file, timeout=600)
    else:
        print(f"Europarl archive already exists: {euro_file} ({fmt_bytes(os.path.getsize(euro_file))})")

    euro_docs = []
    euro_seen = set()
    euro_start = time.time()

    print("Opening Europarl archive...")
    with tarfile.open(euro_file, "r:gz") as tf:
        members = tf.getmembers()
        txt_members = [m for m in members if m.isfile() and m.name.endswith(".txt")]

        print(f"Total archive members: {len(members)}")
        print(f"Text files to inspect: {len(txt_members)}")

        # Raise cap so corpus size is large enough even without DBpedia
        euro_cap = 32000

        for idx, m in enumerate(txt_members, start=1):
            if idx % 25 == 0 or idx == 1:
                elapsed = time.time() - euro_start
                print(
                    f"Europarl file {idx}/{len(txt_members)} | "
                    f"documents so far: {len(euro_docs)} | elapsed: {elapsed:.1f}s"
                )

            f = tf.extractfile(m)
            if not f:
                continue

            try:
                text = f.read().decode(errors="ignore")
            except Exception as e:
                print(f"[WARN] Failed reading {m.name}: {e}")
                continue

            parts = re.split(r"\n\s*\n+", text)

            for i, p in enumerate(parts):
                p = clean(p)
                if len(p.split()) > 40:
                    add_doc(euro_docs, euro_seen, "Europarl", f"{m.name}_{i}", p, {"file": m.name})

                if len(euro_docs) % 2000 == 0 and len(euro_docs) > 0:
                    elapsed = time.time() - euro_start
                    print(
                        f"Europarl docs parsed: {len(euro_docs)} | "
                        f"current file: {m.name} | elapsed: {elapsed:.1f}s"
                    )

                if len(euro_docs) >= euro_cap:
                    print(f"Reached Europarl cap of {euro_cap} documents.")
                    break

            if len(euro_docs) >= euro_cap:
                break

    print(f"Europarl documents: {len(euro_docs)}")
    euro_path = f"{output_dir}/europarl.jsonl"
    write_jsonl(euro_docs, euro_path)
    all_docs.extend(euro_docs)

    # =========================================================
    # MERGE + CHUNK
    # =========================================================
    print("Writing merged corpus...")
    merged_path = f"{output_dir}/corpus.jsonl"
    write_jsonl(all_docs, merged_path)

    print("Chunking corpus...")
    chunks = []
    chunk_start = time.time()

    for i, d in enumerate(all_docs):
        for j, c in enumerate(chunk_text(d["text"])):
            chunks.append({
                "doc_id": i,
                "chunk_id": f"{i}_{j}",
                "source": d["source"],
                "title": d["title"],
                "text": c,
                "meta": d.get("meta", {})
            })

        if (i + 1) % 2000 == 0:
            elapsed = time.time() - chunk_start
            print(
                f"Chunked {i+1}/{len(all_docs)} documents | "
                f"chunks so far: {len(chunks)} | elapsed: {elapsed:.1f}s"
            )

    chunk_path = f"{output_dir}/corpus_chunked.jsonl"
    write_jsonl(chunks, chunk_path)

    result = {
        "documents": len(all_docs),
        "chunks": len(chunks),
        "n_millercenter": len(miller_docs),
        "n_europarl": len(euro_docs),
        "millercenter_jsonl": miller_path,
        "europarl_jsonl": euro_path,
        "merged_jsonl": merged_path,
        "chunked_jsonl": chunk_path,
        "output_dir": output_dir,
    }

    print("Done.")
    print(result)
    return result

# Test case -- this works as of 5 Apr 2026 (Wilbert)

result = build_politics_rag_corpus("politics_rag")
print(result)

"""Build Politics Vector Store"""

!pip install chromadb sentence-transformers

import os
import json
import chromadb
from chromadb.utils import embedding_functions
from tqdm import tqdm

def create_politics_vector_store(
    jsonl_path="politics_rag/corpus_chunked.jsonl",
    persist_directory="politics_vector_store"
):
    """
    Reads the chunked Politics corpus (Miller Center & Europarl)
    and builds a ChromaDB vector store.
    """

    if not os.path.exists(jsonl_path):
        raise FileNotFoundError(f"Cannot find {jsonl_path}. Did Wilbert's cell finish running?")

    print(f"Initializing ChromaDB persistent client at ./{persist_directory}")
    client = chromadb.PersistentClient(path=persist_directory)

    # Initialize the embedding function
    print("Loading all-MiniLM-L6-v2 embedding function...")
    sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name="all-MiniLM-L6-v2"
    )

    # Create the collection
    collection = client.get_or_create_collection(
        name="politics_knowledge_base",
        embedding_function=sentence_transformer_ef,
        metadata={"description": "CrossNER Politics subset RAG corpus (Miller Center & Europarl)"}
    )

    documents = []
    metadatas = []
    ids = []

    print("Reading JSONL records and preparing metadata...")
    with open(jsonl_path, 'r', encoding='utf-8') as f:
        for line in f:
            record = json.loads(line)

            chunk_id = record["chunk_id"]
            text = record["text"]

            # Flatten metadata for ChromaDB compatibility
            meta = record.get("meta", {})
            flat_meta = {
                "source": record.get("source", "Unknown"),
                "title": record.get("title", "Untitled")
            }

            # Miller Center specific metadata
            if "president" in meta:
                flat_meta["president"] = str(meta["president"])
            if "date" in meta:
                flat_meta["date"] = str(meta["date"])
            if "url" in meta:
                flat_meta["url"] = str(meta["url"])

            # Europarl specific metadata
            if "file" in meta:
                flat_meta["file"] = str(meta["file"])

            documents.append(text)
            metadatas.append(flat_meta)
            ids.append(chunk_id)

    total_chunks = len(ids)
    print(f"Found {total_chunks} chunks. Beginning embedding and database insertion...")

    batch_size = 5461

    for i in tqdm(range(0, total_chunks, batch_size), desc="Uploading to Chroma"):
        end_idx = min(i + batch_size, total_chunks)
        collection.add(
            documents=documents[i:end_idx],
            metadatas=metadatas[i:end_idx],
            ids=ids[i:end_idx]
        )

    print(f"\nSuccess! Politics Vector Store built at ./{persist_directory}")

if __name__ == "__main__":
    create_politics_vector_store()

"""Push to Google Drive"""

'''import shutil
import os
from google.colab import drive

# 1. Mount your Google Drive
# This will prompt a popup asking for permission to access your Drive
drive.mount('/content/drive')

# 2. Define the local Colab source and the Google Drive destination
source_folder = "politics_vector_store"
destination_folder = "/content/drive/MyDrive/NLP_Project/politics_vector_store"

# 3. Copy the database folder to Google Drive
if not os.path.exists(source_folder):
    print(f"Error: {source_folder} not found. Ensure the vector store build finished successfully.")
else:
    print(f"Transferring {source_folder} to {destination_folder}...")

    # dirs_exist_ok=True prevents crashes if a folder with that name already exists
    shutil.copytree(source_folder, destination_folder, dirs_exist_ok=True)

    print("Successfully pushed the Politics vector store to Google Drive /NLP_Project!")'''

"""Push .jsonl to Google Drive"""

'''import shutil
import os
from google.colab import drive

# 1. Mount Drive
drive.mount('/content/drive')

# 2. Define paths
politics_source = "politics_rag"
politics_dest = "/content/drive/MyDrive/NLP_Project/politics_rag_data"

# 3. Push the Politics data
if os.path.exists(politics_source):
    print(f"Transferring {politics_source} to {politics_dest}...")
    shutil.copytree(politics_source, politics_dest, dirs_exist_ok=True)
    print("✅ Politics JSONL files successfully backed up to your shared Drive!")
else:
    print(f"⚠️ Error: {politics_source} folder not found. Did the cells above finish running?")'''