# -*- coding: utf-8 -*-
"""data_prep_anatomical_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e96ycByz5YIYV4mYbN90ZMpyHmrVZrmx
"""

def build_biomedical_rag_corpus(output_dir="biomedical_rag"):
    """
    Build a RAG-ready biomedical corpus from:
      1) MeSH
      2) Disease Ontology
      3) DrugCentral

    Outputs:
      - mesh.jsonl
      - disease_ontology.jsonl
      - drugcentral.jsonl
      - biomedical_rag_corpus.jsonl
      - biomedical_rag_corpus_chunked.jsonl
    """

    import os
    import re
    import json
    import csv
    import gzip
    from collections import defaultdict

    import requests
    import xml.etree.ElementTree as ET

    os.makedirs(output_dir, exist_ok=True)

    session = requests.Session()
    session.headers.update({"User-Agent": "Mozilla/5.0 biomedical-rag-builder/1.0"})

    def download(url, path, timeout=120):
        r = session.get(url, stream=True, timeout=timeout)
        r.raise_for_status()
        with open(path, "wb") as f:
            for chunk in r.iter_content(1024 * 1024):
                if chunk:
                    f.write(chunk)

    def clean_text(text):
        if text is None:
            return ""
        text = re.sub(r"\s+", " ", str(text)).strip()
        return text

    def write_jsonl(records, path):
        with open(path, "w", encoding="utf-8") as f:
            for r in records:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")

    def chunk_text(text, size=200, overlap=40):
        words = text.split()
        if not words:
            return []
        step = max(1, size - overlap)
        chunks = []
        for i in range(0, len(words), step):
            chunk = " ".join(words[i:i + size]).strip()
            if len(chunk.split()) > 20:
                chunks.append(chunk)
            if i + size >= len(words):
                break
        return chunks

    def find_latest_mesh_url():
        index_url = "https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/xmlmesh/"
        html = session.get(index_url, timeout=60).text

        matches = re.findall(r'href="(desc\d{4}\.xml)"', html, flags=re.IGNORECASE)
        if not matches:
            raise RuntimeError("Could not find a MeSH descriptor XML file in the MeSH directory listing.")

        latest_file = sorted(set(matches))[-1]
        return index_url + latest_file

    def find_drugcentral_links():
        """
        DrugCentral download page currently links:
        - drug.target.interaction.tsv.gz
        - structures.smiles.tsv
        We first try to scrape the current page. If that fails, we fall back to
        the currently-linked file paths.
        """
        page_url = "https://drugcentral.org/download"
        html = session.get(page_url, timeout=60).text

        tsv_match = re.search(
            r'href="(https?://[^"]*drug\.target\.interaction\.tsv\.gz|/[^"]*drug\.target\.interaction\.tsv\.gz)"',
            html,
            flags=re.IGNORECASE,
        )
        smiles_match = re.search(
            r'href="(https?://[^"]*structures\.smiles\.tsv|/[^"]*structures\.smiles\.tsv)"',
            html,
            flags=re.IGNORECASE,
        )

        def absolutize(href):
            if href.startswith("http://") or href.startswith("https://"):
                return href
            return "https://drugcentral.org" + href

        if tsv_match:
            tsv_url = absolutize(tsv_match.group(1))
        else:
            # Fallback based on current official page links
            tsv_url = "https://unmtid-dbs.net/download/DrugCentral/2021_09_01/drug.target.interaction.tsv.gz"

        if smiles_match:
            smiles_url = absolutize(smiles_match.group(1))
        else:
            # Fallback based on current official page links
            smiles_url = "https://unmtid-dbs.net/download/DrugCentral/2021_09_01/structures.smiles.tsv"

        return tsv_url, smiles_url

    all_records = []

    # ------------------------------------------------------------------
    # 1) MeSH
    # ------------------------------------------------------------------
    mesh_url = find_latest_mesh_url()
    mesh_xml = os.path.join(output_dir, os.path.basename(mesh_url))

    if not os.path.exists(mesh_xml):
        print(f"Downloading MeSH from {mesh_url} ...")
        download(mesh_url, mesh_xml)

    with open(mesh_xml, "r", encoding="utf-8", errors="ignore") as f:
        head = f.read(500)

    if "<DescriptorRecordSet" not in head and "<?xml" not in head:
        raise RuntimeError(
            f"{mesh_xml} does not look like valid MeSH XML. "
            "You may have downloaded an HTML error page instead."
        )

    mesh_records = []
    tree = ET.parse(mesh_xml)
    root = tree.getroot()

    for record in root.findall(".//DescriptorRecord"):
        name = clean_text(record.findtext(".//DescriptorName/String"))
        scope = clean_text(record.findtext(".//ScopeNote"))

        synonyms = []
        for term in record.findall(".//Term/String"):
            s = clean_text(term.text)
            if s and s != name:
                synonyms.append(s)

        text_parts = []
        if scope:
            text_parts.append(scope)
        if synonyms:
            text_parts.append("Synonyms: " + "; ".join(sorted(set(synonyms))[:20]))

        if name and text_parts:
            mesh_records.append({
                "source": "MeSH",
                "title": name,
                "text": clean_text(" ".join(text_parts))
            })

    write_jsonl(mesh_records, os.path.join(output_dir, "mesh.jsonl"))
    all_records.extend(mesh_records)

    # ------------------------------------------------------------------
    # 2) Disease Ontology
    # ------------------------------------------------------------------
    do_url = "https://purl.obolibrary.org/obo/doid.obo"
    do_file = os.path.join(output_dir, "doid.obo")

    if not os.path.exists(do_file):
        print("Downloading Disease Ontology ...")
        download(do_url, do_file)

    do_records = []
    with open(do_file, "r", encoding="utf-8", errors="ignore") as f:
        blocks = f.read().split("\n[Term]\n")

    for block in blocks:
        name = ""
        definition = ""
        synonyms = []

        for line in block.splitlines():
            if line.startswith("name:"):
                name = clean_text(line.replace("name:", "", 1))
            elif line.startswith("def:"):
                m = re.search(r'"(.*?)"', line)
                if m:
                    definition = clean_text(m.group(1))
            elif line.startswith("synonym:"):
                m = re.search(r'"(.*?)"', line)
                if m:
                    synonyms.append(clean_text(m.group(1)))

        if name:
            text_parts = []
            if definition:
                text_parts.append(definition)
            if synonyms:
                text_parts.append("Synonyms: " + "; ".join(sorted(set(synonyms))[:20]))

            do_records.append({
                "source": "DiseaseOntology",
                "title": name,
                "text": clean_text(" ".join(text_parts))
            })

    write_jsonl(do_records, os.path.join(output_dir, "disease_ontology.jsonl"))
    all_records.extend(do_records)

    # ------------------------------------------------------------------
    # 3) DrugCentral
    # ------------------------------------------------------------------
    import csv
    import gzip
    from collections import defaultdict

    drugcentral_records = []

    tsv_url, smiles_url = find_drugcentral_links()

    drug_tsv_gz = os.path.join(output_dir, "drugcentral_drug_target.tsv.gz")
    if not os.path.exists(drug_tsv_gz):
        print(f"Downloading DrugCentral drug-target TSV from {tsv_url} ...")
        download(tsv_url, drug_tsv_gz)

    smiles_file = os.path.join(output_dir, os.path.basename(smiles_url))
    if not os.path.exists(smiles_file):
        print(f"Downloading DrugCentral SMILES file from {smiles_url} ...")
        download(smiles_url, smiles_file)

    drug_map = defaultdict(lambda: {
        "targets": set(),
        "actions": set(),
        "genes": set(),
        "ids": set(),
    })

    # --- inspect and parse TSV defensively ---
    with gzip.open(drug_tsv_gz, "rt", encoding="utf-8", errors="ignore") as f:
        reader = csv.DictReader(f, delimiter="\t")
        headers = reader.fieldnames or []
        print("DrugCentral TSV headers:", headers)

        def first_present(row, candidates):
            for c in candidates:
                if c in row and row[c]:
                    return clean_text(row[c])
            return ""

        for row in reader:
            drug_name = first_present(row, [
                "drug_name", "name", "inn", "ingredient_name",
                "drug", "drug_name_standardized", "drugname"
            ])
            if not drug_name:
                continue

            target = first_present(row, [
                "target_name", "target", "gene_name", "target_gene_name"
            ])
            action = first_present(row, [
                "action_type", "action", "interaction_type", "moa"
            ])
            gene = first_present(row, [
                "gene", "gene_symbol", "target_gene_symbol", "symbol"
            ])
            dc_id = first_present(row, [
                "struct_id", "drugcentral_id", "id"
            ])

            if target:
                drug_map[drug_name]["targets"].add(target)
            if action:
                drug_map[drug_name]["actions"].add(action)
            if gene:
                drug_map[drug_name]["genes"].add(gene)
            if dc_id:
                drug_map[drug_name]["ids"].add(dc_id)

    # --- parse SMILES file and use it as fallback / enrichment ---
    smiles_meta = defaultdict(dict)

    with open(smiles_file, "r", encoding="utf-8", errors="ignore") as f:
        reader = csv.DictReader(f, delimiter="\t")
        smiles_headers = reader.fieldnames or []
        print("DrugCentral SMILES headers:", smiles_headers)

        def first_present(row, candidates):
            for c in candidates:
                if c in row and row[c]:
                    return clean_text(row[c])
            return ""

        for row in reader:
            drug_name = first_present(row, ["INN", "drug_name", "name", "inn"])
            if not drug_name:
                continue

            smiles = first_present(row, ["SMILES", "smiles"])
            inchi = first_present(row, ["InChI", "inchi"])
            cas = first_present(row, ["CAS_RN", "CAS", "cas"])
            dc_id = first_present(row, ["ID", "id", "struct_id", "drugcentral_id"])

            if smiles:
                smiles_meta[drug_name]["smiles"] = smiles
            if inchi:
                smiles_meta[drug_name]["inchi"] = inchi
            if cas:
                smiles_meta[drug_name]["cas"] = cas
            if dc_id:
                smiles_meta[drug_name]["drugcentral_id"] = dc_id

    # If the drug-target TSV gave nothing, fall back to SMILES file alone
    all_drug_names = set(drug_map.keys()) | set(smiles_meta.keys())

    for drug_name in sorted(all_drug_names):
        info = drug_map.get(drug_name, {
            "targets": set(), "actions": set(), "genes": set(), "ids": set()
        })

        text_parts = [drug_name]
        if info["targets"]:
            text_parts.append("Targets: " + "; ".join(sorted(info["targets"])[:20]))
        if info["actions"]:
            text_parts.append("Actions: " + "; ".join(sorted(info["actions"])[:10]))
        if info["genes"]:
            text_parts.append("Genes: " + "; ".join(sorted(info["genes"])[:10]))

        meta = {}
        if info["ids"]:
            meta["drugcentral_ids"] = sorted(info["ids"])[:10]
        if drug_name in smiles_meta:
            meta.update(smiles_meta[drug_name])

        drugcentral_records.append({
            "source": "DrugCentral",
            "title": drug_name,
            "text": clean_text(" ".join(text_parts)),
            "meta": meta
        })

    write_jsonl(drugcentral_records, os.path.join(output_dir, "drugcentral.jsonl"))
    all_records.extend(drugcentral_records)

    # ------------------------------------------------------------------
    # 4) Merge corpus
    # ------------------------------------------------------------------
    merged = os.path.join(output_dir, "biomedical_rag_corpus.jsonl")
    write_jsonl(all_records, merged)

    # ------------------------------------------------------------------
    # 5) Chunk corpus
    # ------------------------------------------------------------------
    chunk_file = os.path.join(output_dir, "biomedical_rag_corpus_chunked.jsonl")
    chunks = []

    for i, doc in enumerate(all_records):
        for j, c in enumerate(chunk_text(doc["text"])):
            chunks.append({
                "doc_id": i,
                "chunk_id": f"{i}_{j}",
                "source": doc["source"],
                "title": doc["title"],
                "text": c,
                "meta": doc.get("meta", {})
            })

    write_jsonl(chunks, chunk_file)

    return {
        "documents": len(all_records),
        "chunks": len(chunks),
        "n_mesh": len(mesh_records),
        "n_disease_ontology": len(do_records),
        "n_drugcentral": len(drugcentral_records),
        "mesh_jsonl": os.path.join(output_dir, "mesh.jsonl"),
        "disease_ontology_jsonl": os.path.join(output_dir, "disease_ontology.jsonl"),
        "drugcentral_jsonl": os.path.join(output_dir, "drugcentral.jsonl"),
        "merged_jsonl": merged,
        "chunked_jsonl": chunk_file,
        "output_dir": output_dir,
    }

result = build_biomedical_rag_corpus("biomedical_rag")
print(result)

def build_biomedical_rag_corpus_2(output_dir="biomedical_rag_2"):
    """
    Build a supplemental RAG-ready biomedical corpus from:
      1) Uberon (Multi-species Anatomy Ontology)
      2) Human Phenotype Ontology (HPO)
      3) Cell Ontology (CL)

    Outputs:
      - uberon.jsonl
      - hpo.jsonl
      - cell_ontology.jsonl
      - biomedical_rag_corpus_2.jsonl
      - biomedical_rag_corpus_2_chunked.jsonl
    """

    import os
    import re
    import json
    import requests

    os.makedirs(output_dir, exist_ok=True)

    session = requests.Session()
    session.headers.update({"User-Agent": "Mozilla/5.0 biomedical-rag-builder-2/1.0"})

    def download(url, path, timeout=120):
        r = session.get(url, stream=True, timeout=timeout)
        r.raise_for_status()
        with open(path, "wb") as f:
            for chunk in r.iter_content(1024 * 1024):
                if chunk:
                    f.write(chunk)

    def clean_text(text):
        if text is None:
            return ""
        text = re.sub(r"\s+", " ", str(text)).strip()
        return text

    def write_jsonl(records, path):
        with open(path, "w", encoding="utf-8") as f:
            for r in records:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")

    def chunk_text(text, size=200, overlap=40):
        words = text.split()
        if not words:
            return []
        step = max(1, size - overlap)
        chunks = []
        for i in range(0, len(words), step):
            chunk = " ".join(words[i:i + size]).strip()
            if len(chunk.split()) > 20:
                chunks.append(chunk)
            if i + size >= len(words):
                break
        return chunks

    def parse_obo_file(file_path, source_name):
        """Reuses Wilbert's OBO parsing logic for uniform extraction."""
        records = []
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            # Split by [Term] blocks
            blocks = f.read().split("\n[Term]\n")

        # Skip the first block (it's just the file header metadata)
        for block in blocks[1:]:
            name = ""
            definition = ""
            synonyms = []

            for line in block.splitlines():
                if line.startswith("name:"):
                    name = clean_text(line.replace("name:", "", 1))
                elif line.startswith("def:"):
                    m = re.search(r'"(.*?)"', line)
                    if m:
                        definition = clean_text(m.group(1))
                elif line.startswith("synonym:"):
                    m = re.search(r'"(.*?)"', line)
                    if m:
                        synonyms.append(clean_text(m.group(1)))

            if name:
                text_parts = []
                if definition:
                    text_parts.append(definition)
                if synonyms:
                    text_parts.append("Synonyms: " + "; ".join(sorted(set(synonyms))[:20]))

                # Only append if we actually have text beyond just the name
                if text_parts:
                    records.append({
                        "source": source_name,
                        "title": name,
                        "text": clean_text(" ".join(text_parts))
                    })
        return records

    all_records = []

    # Define our 3 new datasets and their official PURL download links
    datasets = [
        ("Uberon", "http://purl.obolibrary.org/obo/uberon.obo", "uberon.obo", "uberon.jsonl"),
        ("HPO", "http://purl.obolibrary.org/obo/hp.obo", "hp.obo", "hpo.jsonl"),
        ("CellOntology", "http://purl.obolibrary.org/obo/cl.obo", "cl.obo", "cell_ontology.jsonl")
    ]

    counts = {}

    # 1) Download and Parse each OBO file
    for source_name, url, obo_filename, jsonl_filename in datasets:
        obo_path = os.path.join(output_dir, obo_filename)
        jsonl_path = os.path.join(output_dir, jsonl_filename)

        if not os.path.exists(obo_path):
            print(f"Downloading {source_name} from {url} ...")
            download(url, obo_path)

        print(f"Parsing {source_name}...")
        records = parse_obo_file(obo_path, source_name)

        write_jsonl(records, jsonl_path)
        all_records.extend(records)
        counts[source_name] = len(records)

    # 2) Merge corpus
    merged = os.path.join(output_dir, "biomedical_rag_corpus_2.jsonl")
    write_jsonl(all_records, merged)

    # 3) Chunk corpus
    chunk_file = os.path.join(output_dir, "biomedical_rag_corpus_2_chunked.jsonl")
    chunks = []

    for i, doc in enumerate(all_records):
        for j, c in enumerate(chunk_text(doc["text"])):
            chunks.append({
                "doc_id": i,
                "chunk_id": f"{i}_{j}",
                "source": doc["source"],
                "title": doc["title"],
                "text": c,
                "meta": {}  # OBO files don't have complex nested meta, keeping it uniform
            })

    write_jsonl(chunks, chunk_file)

    return {
        "documents": len(all_records),
        "chunks": len(chunks),
        "counts": counts,
        "merged_jsonl": merged,
        "chunked_jsonl": chunk_file,
        "output_dir": output_dir,
    }

result = build_biomedical_rag_corpus_2("biomedical_rag_2")
print("\n--- Generation Complete ---")
print(result)